FROM php:7.1.33-apache

RUN sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g; s|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list \
&& apt-get -o Acquire::Check-Valid-Until=false update \
&& apt-get install -y \
apache2 \
bash \
curl \
imagemagick \
libmagickwand-dev \
libgif-dev \
libjpeg-dev \
libpng-dev \
libzip-dev \
openssl \
ssl-cert \
vim \
zip \
unzip \
&& docker-php-ext-install \
exif \
gd \
mbstring \
mysqli \
pdo \
pdo_mysql \
&& pecl install imagick \
&& docker-php-ext-enable imagick \
&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
&& rm -rf /var/lib/apt/lists/*

COPY ./php.ini $PHP_INI_DIR/php.ini
COPY ./ssl-legacy.conf /etc/apache2/sites-available/ssl.conf

RUN a2enmod ssl && a2enmod rewrite && a2ensite ssl
